In [9]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [14]:
#1.  How many negative numbers are there?
# There are 4 negative numbers: -2,-1,-6,-7
a_negatives = a[a < 0]
a_negatives
total_a_negatives = len(a_negatives)
total_a_negatives

4

In [23]:
#2.  How many positive numbers are there?
# There are 8 positive numbers: 4, 10, 12, 23, 3
a_positives = len(a[a > 0])
a_positives

5

In [28]:
#3. How many even positive numbers are there?
# There are 5 even positive numbers: 4, 10, 12, 23,  3
a_even_positives = a[a % 2 == 0]
a_even_positives = a[a > 0]
a_even_positives_total = len(a_even_positives)
a_even_positives_total

#If we have expressions that produce an array of boolean, we can string them together with the &
#EX) even_positives = a[(a>0)] & (a % 2 == 0)

5

In [31]:
#4.  If you were to add 3 to each data point, how many positive numbers would there be?
# There are 10 positive numbers: 7, 13, 15, 26,  1,  2,  3,  3,  3,  6
b = a + 3
b_positives = len(b[b > 0])
b_positives


10

In [35]:
#5. If you squared each number, what would the new mean and standard deviation be?
#SQUARED
a_squared = a ** 2
a_squared
#STD = 144.024
a_squared_std = a_squared.std()
a_squared_std
#MEAN = 74.0
a_squared_mean = a_squared.mean()
a_squared_mean


74.0

In [41]:
#6.  A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.
a_mean = a.mean()
a_mean
a_centered = a - a_mean
a_centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [36]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [45]:
#7. Calculate the z-score for each data point. Recall that the z-score is given by:
# x = raw score, m = population mean, o = populations std
# mean = 3
# std = 8.06225774829855
a_mean = a.mean()
a_std = a.std()
a_mean
a_std

a_zscore = a - a_mean
a_zscore = a_zscore / a_std
a_zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
sum_of_a

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)
mean_of_a

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n ** 2 for n in a ]
squares_of_a
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = 
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [47]:
#8b.
#Hint: 

b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [48]:
min(a)

1

In [49]:
min(b)

[3, 4, 5]

In [52]:
# Exercise 2 - refactor the following to use numpy:
min_of_b = min(b[0]) if min(b[1]) <= min(b[1]) else min([1])
min_of_b

3

In [54]:
c = []
for numbers in b:
    for n in numbers:
        c.append(n)
min(c)

3

In [55]:
# b.min() doesnt work because you have to turn it into an array first
b = np.array(b)
b.min()

3

In [8]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(a)

In [9]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = a.sum()
sum_of_a

55

In [11]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = a.min()
min_of_a

1

In [12]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = a.max()

In [13]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = a.mean()
mean_of_a

5.5

In [15]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = a[a * a]
product_of_a

total = 1
for n in a:
    total *= n
total

IndexError: index 16 is out of bounds for axis 0 with size 10

In [17]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
# Exercise 1 - refactor the following to use numpy. 
#Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

# Refactor

sum_of_b = []

33

In [ ]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  



In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])




In [ ]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number


In [ ]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


In [ ]:

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
b[b % 2 == 0]

In [20]:

# Exercise 9 - print out the shape of the array b.
b.shape
# Exercise 10 - transpose the array b.
b.T
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(6)
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)
c.min(), c.max(), c.sum(), c.prod()

# Exercise 2 - Determine the standard deviation of c.
c.std()
# Exercise 3 - Determine the variance of c.
c.var()
# Exercise 4 - Print out the shape of the array c
c.shape
# Exercise 5 - Transpose c and print out transposed result.
c.T
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c).sum()
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(np.dot(c,c.T)).sum()
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)
# Exercise 4 - Find all the negative numbers in d
d = np.array(d)
d[d < 0]
# Exercise 5 - Find all the positive numbers in d
d[d > 0]
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)
# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.
d.shape
# Exercise 9 - Transpose and then print out the shape of d.
d.T.shape
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)
