# Numpy

    - Numpy is one of the main reasons why python is so powerful and popular for scientific computing
    - Super fast, numpy arrays are implemented in C, which makes numpy very fast
    - Numpy is the most popular linear alebra library for python
    Provides loop-lik behavior w/o the overhead of loops or list comprehensions(vectorized operations)
    - Provides list + loop + conditional behavior for filtering arrays
    

## Now What?
    - Start working with numpy arrays!
    -np.array([1,2,3]) to create numpy array!
    - We'll start using built-in numpy functions all the time:
        -min, max, mean, sum, std
        -np.median
    - Learn to use some numpy vectorized operations
    - Learn how to create arrays of booleans to filter results
 

In [1]:
import numpy as np

In [2]:
%%timeit
[x ** 2 for x in range(1,1_000_000)]

316 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
np.arange(1,1_000_000) ** 2

3.71 ms ± 86.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
# Why is numpy faster than python?
# C si "closer to the metal" than Python
# Assembly is closer to the metal than C
# and Processor instruction sets == are the metal!
316/3.17

99.6845425867508

In [7]:
# Let's make our first numpy array:
x = [1,2,3,4,5]
x = np.array(x) #array is a function that takes in a argument and prints out an array
x, type(x)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [9]:
# Shape is a property not a function.  Tells us the shape of out n-dimensiional array
x.shape

(5,)

In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,0,9]
])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [11]:
type(matrix)

numpy.ndarray

In [13]:
# List index syntax works on numpy arrays!
matrix[0]


array([1, 2, 3])

In [14]:
# matrix[row][column]
matrix[0][0]

1

In [15]:
matrix[0][1]

2

In [17]:
matrix[0][2]

3

In [18]:
# We can also use splicing syntax
x, x[1:3]

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [19]:
a = np.array(range(1,100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
# This creates a tuple.  Notice the parentheses.
a.sum(), a.mean(), a.min(), a.max(), a.std()


(4950, 50.0, 1, 99, 28.577380332470412)

In [21]:
#median is different (there's some other functions that work similaryly)
np.median(a)


50.0

In [22]:
b = np.array([2,3,4,5])
should_include_elements = np.array([False, True, False, True])
b[should_include_elements]

array([3, 5])

## Arrays of Booleans == Beating Heart of Filtering/Transforming Arrays
    - This is how we can do loop-like stuff w/o loops
    

In [23]:
x = np.array([1,2,3,4,5])

In [24]:
x == 3

array([False, False,  True, False, False])

In [25]:
#Our comparison operators usually give us back booeleans

In [26]:
x < -9

array([False, False, False, False, False])

In [27]:
x > 3


array([False, False, False,  True,  True])

In [29]:
# Whatever we do to produce an array of booleans, this "spell" is called "boolean masking" and folks may say "array filtering
only_threes = x ==3
x[only_threes]

array([3])

In [30]:
# We don't need the extra variable, however, we can do the following:
# I read this code almost like SQL in my head:
# Select x where x is eqal to 3
x[x==3]

array([3])

In [31]:
# Select x where x is less than zero
x[x < 0]

array([], dtype=int64)

In [32]:
# Select x where x is greater than 3
x[x>3]

array([4, 5])

In [33]:
# Select x where x divided by two leaves no remainder
evens_from_x = x[x % 2 == 0]
evens_from_x

array([2, 4])

In [37]:
# In the python admissions test, there was a question called "remove_evens" where you write a function that removes evens
# In base python, this is a loop w/ a conditional and another operation to appen to a list, or a list comprehension

def remove_evens(x):
    x = np.array(x)
    return x[x % 2 == 0]

remove_evens([2,3,34,5,6,24,12,3,24,3,3,23,23,23,10])

array([ 2, 34,  6, 24, 12, 24, 10])

In [39]:
x = np.array([1,2,"3",4])
x

array(['1', '2', '3', '4'], dtype='<U21')

## Intro to vectorization
    - Loop like behavior on an array w/o the loop

In [40]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# We can add 1 without a loop!
x + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Let's make an array of random numbers
# The start is inclusive, end is exclusive
# Sp the following line is like rolling a 20 sided die
np.random.randint(1,21)


19

In [43]:
# 3rd argument is the size (or the number of random numbers)
x = np.random.randint(1,21,10)
x

array([13,  4,  9, 16,  1, 19,  2,  1, 10, 13])

In [44]:
# Let's make python fall on its face

a = [1,2,3]

# In python, how would we add one to every item on this list?
[n + 1 for n in a]

[2, 3, 4]

In [45]:
x + 1

array([14,  5, 10, 17,  2, 20,  3,  2, 11, 14])

In [46]:
x / 10

array([1.3, 0.4, 0.9, 1.6, 0.1, 1.9, 0.2, 0.1, 1. , 1.3])

In [47]:
x * x

array([169,  16,  81, 256,   1, 361,   4,   1, 100, 169])

In [48]:
x * x -2 + 3 * x

array([206,  26, 106, 302,   2, 416,   8,   2, 128, 206])

In [49]:
x + x

array([26,  8, 18, 32,  2, 38,  4,  2, 20, 26])

In [50]:
x - 2*x

array([-13,  -4,  -9, -16,  -1, -19,  -2,  -1, -10, -13])

In [51]:
# There are many more linear algebra features
np.dot(x,x)

1158

In [52]:
np.linalg.norm(x)

34.02939905434711

In [53]:
beatles = np.array(["ringo", "george", "paul", "john"])

beatles == 'ringo'

array([ True, False, False, False])

In [54]:
beatles[beatles != 'ringo']

array(['george', 'paul', 'john'], dtype='<U6')

In [55]:
beatles[beatles == 'ringo']

array(['ringo'], dtype='<U6')